# Generated by Django 4.0.4 on 2022-05-15 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('user_role', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogs_id', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('tilte', models.CharField(max_length=1000)),
                ('content', models.CharField(max_length=15000)),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('pub_date', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogpost.user')),
            ],
        ),
    ]
