# Generated by Django 4.0.4 on 2022-05-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blogs_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
